# -*- coding: utf-8 -*-
"""Copie de Python error types checkpoint.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1smDHl3Ff3kNeeaGQ_-6B-kzzLkOahCYY

# Rectify the code in each cell and **explain the error in comments**

### index error
"""

mylist=[14, "hello", 967]
mylist[2] #the list contains only 3 items

import pandas
import numpy #numpy and pandas were written wrongly

"""# syntax error"""

print("python errors") #parentheses were missing and print was written Print

"""# key error"""

mydictionnary={True:"hello",False:"bye", '3':"python"}

"""# indentation error"""

i=14
while i<4:
   print(i) #indentation after while loop
i+=1

"""# StopIteration"""

it=iter([1,2,3])
next(it)
next(it)
next(it)
#the next() function went beyond the iterator items

"""# TypeError

"""

'15'+'15' # operation is applied to an object of an inappropriate type

"""# ValueError"""

int('20') #inappropriate type

"""# NameError"""

print("python")

"""# ZeroDivisionError"""

x=19/2 #we cant devide by 0